// Generated by CoffeeScript 1.6.3
(function() {
  var timeOut, _constructor;

  timeOut = 60 * 15 * 1000;

  exports.next = function(req) {
    req.session.aSteps.nStep = req.session.aSteps.nStep + 1;
    if (req.session.aSteps.steps[req.session.aSteps.nStep]) {
      return req.session.next(_constructor(req.session.aSteps.steps[req.session.aSteps.nStep]), timeOut);
    } else {
      return console.log("已经没有下一步了");
    }
  };

  exports.again = function(req) {
    return req.session.next(_constructor(req.session.aSteps.steps[req.session.aSteps.nStep]), timeOut);
  };

  exports.start = function(aFuncs, req) {
    req.session.aSteps = {};
    req.session.aSteps.steps = aFuncs;
    req.session.aSteps.nStep = 0;
    return req.session.next(_constructor(req.session.aSteps.steps[0]), timeOut);
  };

  exports._quit = function(params, req, res) {
    if (params.Content === 'quit' || params.Content === '取消' || params.Content === '退出') {
      res.reply("取消成功");
      delete req.session.registeration;
      return true;
    } else {
      return false;
    }
  };

  _constructor = function(func) {
    return function(params, req, res, next, mainNext) {
      if (exports._quit(params, req, res)) {
        return;
      }
      if (params.Event === "CLICK") {
        delete req.session.registeration;
        mainNext();
        return;
      }
      if (typeof func !== void 0) {
        return func(params, req, res, next);
      }
    };
  };

}).call(this);
