// Generated by CoffeeScript 1.6.3
(function() {
  var Steps, accessToken, http, wechatutil;

  Steps = require("ocsteps");

  accessToken = require("../../welab/controllers/access-token.js");

  http = require("http");

  wechatutil = require("welab/controllers/wechat-api/util.js");

  exports.pad = function(num, n) {
    return Array(n - ('' + num).length + 1).join(0) + num;
  };

  exports.toPRC = function(strDate) {
    return new Date(strDate).getTime() + (new Date().getTimezoneOffset() * 60 * 1000);
  };

  exports.updateUserInfo = function(wxid, doc) {
    return helper.db.coll("welab/customers").update({
      wechatid: wxid
    }, {
      $set: doc
    }, function(err, doc) {});
  };

  exports.replyForDb = function(tag, params) {
    var _tag;
    _tag = eval("/^" + tag + "$/i");
    return helper.db.coll("welab/reply").findOne({
      tags: _tag,
      isValid: true
    }, function(err, doc) {
      var reply;
      reply = wechatutil.makeReply(params[0], doc, params[1]);
      return params[2].reply(reply);
    });
  };

}).call(this);
