// Generated by CoffeeScript 1.6.3
(function() {
    var wechatapi, welabExtension;

    wechatapi = require("welab/lib/wechat-api.js");

    welabExtension = require('welab/extension.js');

    exports.load = function() {
        welabExtension.apps.guess = {
            categories: ['图片'],
            type: '互动',
            icon: '/welab/apps/welcome/public/icon_s.png',
            on: true,
            title: '竞猜型',
            desc: '竞猜型',
            btns: [
                {
                    title: '列表',
                    controller: '/lavico/answerQuestion/statistics/statistics_list_1'
                }, {
                    title: '添加',
                    controller: '/lavico/answerQuestion/question/addQuestion?themetype=3'
                }
            ],
            start: function() {
                return this.on = true;
            },
            stop: function() {
                return this.on = false;
            }
        };

        return wechatapi.makeQueue();
    };

}).call(this);


