// Generated by CoffeeScript 1.6.3
(function() {
    var wechatapi, welabExtension;

    wechatapi = require("welab/lib/wechat-api.js");

    welabExtension = require('welab/extension.js');

    exports.load = function() {
        welabExtension.apps.score = {
            categories: ['图片'],
            type: '定制应用',
            icon: '/welab/apps/register/public/icon_s.png',
            on: true,
            title: 'QiangJiFeng',
            desc: 'QiangJiFeng',
            btns: [
                {
                    title: 'Add',
                    controller: '/lavico/answerQuestion/addTheme'
                }, {
                    title: 'List',
                    controller: '/lavico/answerQuestion/themeList'
                }
            ],
            start: function() {
                return this.on = true;
            },
            stop: function() {
                return this.on = false;
            }
        };

        return wechatapi.makeQueue();
    };

}).call(this);
