// Generated by CoffeeScript 1.6.3
(function() {
    var wechatapi, welabExtension;

    wechatapi = require("welab/lib/wechat-api.js");

    welabExtension = require('welab/extension.js');

    exports.load = function() {
        welabExtension.apps.sportsman = {
            categories: ['图片'],
            type: '定制应用',
            icon: '/welab/apps/register/public/icon_s.png',
            on: true,
            title: '型男测试',
            desc: '型男测试',
            btns: [
                {
                    title: '添加',
                    controller: '/lavico/answerQuestion/question/addQuestion'
                }, {
                    title: '列表',
                    controller: '/lavico/answerQuestion/themeList?themetype=1'
                },{
                    title: '统计',
                    controller: '/lavico/answerQuestion/statistics/statistics_list?themetype=1'
                }
            ],
            start: function() {
                return this.on = true;
            },
            stop: function() {
                return this.on = false;
            }
        };

        return wechatapi.makeQueue();
    };

}).call(this);

